### Get access token
POST http://localhost:9000/realms/development/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = spa-client &
username = admin &
password = password &
grant_type = password
> {%
  client.global.set("access_token", response.body.access_token)
%}

###
GET localhost:8080/api/keycloak/users
Authorization: Bearer {{access_token}}

###
GET http://keycloak:8080/realms/development/.well-known/openid-configuration

###
